name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup System
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libcurl4-gnutls-dev
        sudo chmod 744 install-json-c.sh
        sudo ./install-json-c.sh
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig        
    - name: make
      run: make
